server:
  port: 8086
spring:
  datasource:
    databaseDriverName: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/customer_journey?serverTimezone=Asia/Kathmandu'
    username: rupak
    password: rupak
    maxPool: 5
    maxIdle: 4
    minIdle: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    generate-ddl: true
    show-sql: false
    properties:
      hibernate.ddl-auto: update
      hibernate.generate_statistics: false
      hibernate.show_sql: true
      hibernate.format_sql: false
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true